apiVersion: v1
kind: Deployment
metadata:
  name: yolo-deployment
spec:
  selector:
    matchLabels:
      app: yolo
  replicas: 1
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo-container
        image: python:3.10
        command: ["/bin/bash"]
        args: ["-c", "git clone https://github.com/LahmerMohammed/bmv2-loadbalancer.git && cd bmv2-loadbalancer && chmod +x ./run.sh && ./run.sh && sleep infinity"]
        ports:
        - containerPort: 55555

---

apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  selector:
    app: yolo
  type: NodePort
  ports:
  - name: yolo-port
    port: 55555
    targetPort: 55555
