
apiVersion: v1
kind: Pod
metadata:
  name: yolo-v3
  labels:
    name: yolo
spec:
  containers:
  - name: yolo-container
    image: python:3.10
    args: 
    - "/bin/bash"
    - "-c"
    - "git clone https://github.com/LahmerMohammed/bmv2-loadbalancer.git && cd bmv2-loadbalancer/yolo-service && chmod +x ./run.sh && ./run.sh && sleep infinity"
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 180
      periodSeconds: 5
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
    
    