
apiVersion: v1
kind: Pod
metadata:
  name: yolo-v3-2
  labels:
    name: yolo-2
spec:
  containers:
  - name: yolo-container
    image: localhost:5000/yolov3:v1
    args: 
    - "/bin/bash"
    - "-c"
    - "cd /app && chmod +x ./myapp && ./myapp &&  sleep infinity"
    ports:
    - containerPort: 8000
    resources:
      limits:
        cpu: "7000m"
              
    
    
