
apiVersion: v1
kind: Pod
metadata:
  name: yolo-v3
  labels:
    name: yolo
spec:
  containers:
  - name: yolo-container
    image: localhost:5000/yolov3:v1
    args: 
    - "/bin/bash"
    - "-c"
    - "cd /app && node index.js && sleep infinity"
    ports:
    - containerPort: 8000
    resources:
      limits:
        cpu: "1500m"
        memory: "3Gi"
              
    
    
