
apiVersion: v1
kind: Pod
metadata:
  name: yolo-v3
  labels:
    name: yolo
spec:
  containers:
  - name: yolo-container
    image: localhost:5000/yolov3:v1
    args: 
    - "/bin/bash"
    - "-c"
    - "git clone https://github.com/LahmerMohammed/bmv2-loadbalancer.git && cd bmv2-loadbalancer/ml_model/yolo/api && git checkout v2 && pip3 install gunicorn && chmod +x ./run.sh && ./run.sh && sleep infinity"
    ports:
    - containerPort: 8000
    resources:
      limits:
        cpu: "1500m"
              
    
    
