
apiVersion: v1
kind: Pod
metadata:
  name: yolo-v3
  labels:
    name: yolo
spec:
  containers:
  - name: yolo-container
    image: tensorflow/serving
    args: 
    - "/bin/bash"
    - "-c"
    - "sleep infinity"
    ports:
    - containerPort: 8000
    