
apiVersion: v1
kind: Pod
metadata:
  name: yolo-v3
  labels:
    name: yolo
spec:
  containers:
  - name: yolo-container
    image: python:3.10
    args: 
    - "/bin/bash"
    - "-c"
    - "git clone -b v2 https://github.com/LahmerMohammed/bmv2-loadbalancer.git && cd bmv2-loadbalancer/ml_model/yolo/api && chmod +x ./run.sh && ./run.sh && sleep infinity"
    ports:
    - containerPort: 8000
    resources:
      limits:
        cpu: "2652m"
              
    
    