apiVersion: v1
kind: Service
metadata:
  name: yolo-svc-2
spec:
  selector:
    name: yolo-2
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31111 
  type: NodePort

